#!/bin/bash

function hello() {
   echo "Hello world"
}

if [ $# -lt 1 ]
then
    echo "Usage kvm number [command]"
    exit 1
fi

if [ $1 -lt 1 ]
then
    echo "Assign kvm a number 1-5"
    exit 2
fi

if [ $1 -gt 5 ]
then
    echo "Assign kvm a number 1-5"
    exit 2
fi

echo $(basename -a $0) $1 $2

if [ $# -eq 1 ]
then
    echo "kvm-launch"
fi

if [ $# -gt 1 ]
then
    command="$2"
    echo "The command is: $command"
    shift
    shift
    echo "The arguments are $@"
fi

if [ $command == "hello" ]
then
    hello
fi
