#!/bin/bash

function kvmlaunch() {
    echo "kvmlaunch"
}

function ping() {
    echo "ping $@"
}

function traceroute() {
    echo "traceroute $@"
}

function lsiso() {
    echo "lsiso $@"
}

function mount() {
    echo "mount $@"
}

if [ $# -lt 1 ]
then
    echo "Usage kvm number [command]"
    exit 1
fi

if [ $1 == "help" ]
then
    shift
    kvm-help $@
fi

if [ $1 -lt 1 ]
then
    echo "Assign kvm a number 1-5"
    exit 2
fi

if [ $1 -gt 5 ]
then
    echo "Assign kvm a number 1-5"
    exit 2
fi

if [ $# -eq 1 ]
then
    kvmlaunch
fi

if [ $# -gt 1 ]
then
    command="$2"
    shift
    shift
fi

case $command in
    ping)
        ping $@
        ;;
    traceroute)
        traceroute $@
        ;;
    lsiso)
        lsiso $@
        ;;
    mount)
        mount $@
        ;;
esac
