#!/bin/bash

if [ $# -lt 2 ]
then
    echo "Usage kvm number [command]"
    exit 1
fi

if [ $1 -lt 1 ]
then
    echo "Assign kvm a number 1-5"
    exit 2
fi

if [ $1 -gt 5 ]
then
    echo "Assign kvm a number 1-5"
    exit 2
fi

echo $(basename -a $0) $1 $2
