#!/bin/bash
. ~/.kvmrc
WorkDir=~/.kvm/$1
DomainName="kvm$1.unrealservers.net"
ShareIP="66.181.33.30"
ShareFolder="isos"
ShareIso="ewc.img"

function authenticateWithCurl() {
    local DataString='nickname=&login='"${User}"'&password='"${Password}"'&action_login=Login'
    echo 'Logging in...'
    curl -s --data "${DataString}" 'http://'"${DomainName}"'/auth.asp' -c "${WorkDir}/jar" > /dev/null
}

function loadiso() {
    echo 'Loading iso file'
    curl -s --http1.1 -L -F 'FV_0_vfloppyextern=0' -F "FV_1_vfloppyextern=${ShareIP}" -F "FV_2_vfloppyextern=${ShareFolder}" -F "FV_3_vfloppyextern=${ShareIso}" -F "FV_4_vfloppyexterm=" -F 'FV_5_vfloppyextern=""' -F 'action_vfloppy_smb_set=" Set "' -b "${WorkDir}/jar" "${DomainName}/um.asp" > /dev/null

}

authenticateWithCurl
loadiso
