#!/bin/bash
. ~/.kvmrc
WorkDir=~/.kvm/$1
DomainName="kvm$1.unrealservers.net"
NewPassword=`./pwgen.bare`

if [ $1 -lt 0 ] || [ $1 -gt 5 ]
then
    echo "provide 0 for all kvms or 1-5 for a specific kvm"
    exit 1
fi

function makeWorkingDirectory() {
    mkdir -p ${WorkDir}
}


function authenticateWithCurl() {
    local DataString='nickname=&login='"${User}"'&password='"${Password}"'&action_login=Login'
    echo 'Logging in...'
    curl -s --data "${DataString}" 'http://'"${DomainName}"'/auth.asp' -c "${WorkDir}/jar" > /dev/null
}

function changeClientOneAuthentication() {
    echo 'Changing client one password'
    curl -s --http1.1 -L -F 'FV_0_umusers=client1' -F 'FV_1_umusers=client1' -F 'FV_2_umusers=Client One' -F "FV_3_umusers=${NewPassWord}" -F "FV_4_umusers=${NewPassWord}" -F 'FV_5_umusers=' -F 'FV_6_umusers=' -F 'FV_7_umusers=3' -F 'action_modify_user=Modify' -F 'FV_0_umgroups=' -F 'FV_2_umgroups=' -F '__templates__=umusers umgroups umusers umgroups' -b "${WorkDir}/jar" "${DomainName}/um.asp" > /dev/null

}

function saveClientOnePassword() {
   echo ${NewPassword} > ${WorkDir}/Password
   echo ${NewPassword} > ${WorkDir}/PasswordNato
   echo ${NewPassword} | ./string2nato >> ${WorkDir}/PasswordNato
}

makeWorkingDirectory
authenticateWithCurl
changeClientOneAuthentication
saveClientOnePassword
