#!/bin/bash
. ~/.kvmrc

if [ $1 -lt 0 ] || [ $1 -gt 5 ]
then
    echo "provide 0 for all kvms or 1-5 for a specific kvm"
    exit 1
fi

. ~/.kvm/0/.kvminfo

if [ $1 -eq 0 ]
then
    counter=1;
    for ip in ${kvmips[@]};
    do
        echo -e "\033[01;32m KVM Unit:"
        echo -e " $counter\033[00m"
        counter=$(($counter+1))
        ping -c 2 -q $ip
    done
else
    kvmunit=$1
    kvmunit=$(($kvmunit-1))
    kvmip="${kvmips[$kvmunit]}"
    ping -c 3 -q $kvmip
fi
