#!/bin/bash
. ~/.kvmrc
WorkDir=~/.kvm/$1
DomainName="kvm$1.unrealservers.net"
ShareIP="66.181.33.30"
ShareFolder="isos"
Blank=""
Set=" Set "

if [ $# -lt 2 ]
then
ShareIso="bootimage.iso"
else
ShareIso=$2
fi

function authenticateWithCurl() {
    local DataString='nickname=&login='"${User}"'&password='"${Password}"'&action_login=Login'
    echo 'Logging in...'
    curl -s --data "${DataString}" 'http://'"${DomainName}"'/auth.asp' -c "${WorkDir}/jar" > /dev/null
}

function loadiso() {
    echo 'Loading iso file'
    curl -s -L -F 'FV_1_vmediaoptions=yes' -F 'FV_2_vmediaoptions=yes' -F '__reset_to_defaults__=yes' -F 'FV_0_vfloppyextern=0' -F "FV_1_vfloppyextern=${ShareIP}" -F "FV_2_vfloppyextern=${ShareFolder}" -F "FV_3_vfloppyextern=${ShareIso}" -F 'FV_4_vfloppyextern=' -F 'FV_5_vfloppyextern=' -F 'action_vfloppy_smb_set= Set ' -F 'vfloppy_ms_index=0' -F 'vfloppy_file=' -F '__templates__= vfloppyactive vmediaoptions vfloppyextern vfloppyintern vfloppyactive vmediaoptions vfloppyextern vfloppyintern' -b "${WorkDir}/jar" "${DomainName}/vmedia.asp" > /dev/null
}

authenticateWithCurl
loadiso
