#!/bin/bash
. ~/.kvmrc
WorkDir=~/.kvm/$1
DomainName="kvm$1.unrealservers.net"
ShareIP="66.181.33.30"

function listAvailableIsoFiles() {
    smbclient \\\\${ShareIP}\\isos -Nc ls
}

listAvailableIsoFiles
